### ISSUE TITLE
Feature Request: WordPress implementation

### ISSUE THREAD

**Issue by djrobzilla** [0xGeel/loopgate#24]
I'm not sure how feasible this is, but it'd be amazing to have this available as a WordPress plugin. That's definitely a plugin I'd pay money for! There are two plugins right now for WordPress that offer this functionality: ethpress and "WordPress NFT Token Gating &
Web3 Wallet login". Ethpress requires the manual installation of some sus looking libraries that I'd rather not mess with, and the other one is crazy expensive and offers way more than i think most people who are looking for this kind of functionality actually need.

**Comment by 0xGeel** [comment]
Hi @djrobzilla, posting my Discord reply here for visibility's sake:

---

Unfortunately, though, I'm not sure I can be of direct help here. 

LoopGate is built as a NextJS app, which is fully written in Typescript/Javascript. It's "Serverless", in the sense that it does not have a traditional backend / database that is always there, but rather uses cloud computers to execute the backend functions.

Wordpress is PHP-based, and requires a constant backend server to run. I think it makes more sense to re-write the LoopGate functionality that "make token-gating work" in PHP, then publish those as a PHP plugin. Here are the core functionalities:

- Sign In With Ethereum (SIWE) alongside IronSession. This makes the app secure: only if you can prove ownership of a wallet by signing a message, you get authenticated.
- ConnectKit + WAGMI hooks for interacting with a Loopring / Ethereum wallet.
- (Rate-limited) Loopring API Requests: query data on Loopring L2 to get NFT ownership data.
- Pinata API Requests: query data on Pinata IPFS to unlock content stored on there. 

The issue: my experience in PHP is very limited, and building this PHP plugin greatly affects the development speed of the "regular" LoopGate, which is my priority. I don't know if I even am able to ship this in PHP for WordPress 😪

---

Contributions of any kind are welcome, though. If you feel like taking on this WordPress implementation, I'd be happy to help you out.

**Comment by 0xGeel** [comment]
Hi there @djrobzilla,

You may have seen this already, but I'm posting this here for others to find as well:
🚀  stepwn has graciously provided an open source Wordpress implementation for Token Gating using Loopring NFTs!

See: https://github.com/stepwn/LoopPress
